package com.faceverse.editor.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.faceverse.editor.ui.theme.*
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch

data class ArtStyle(val id: String, val name: String, val emoji: String, val premium: Boolean)
data class HairStyle(val id: String, val name: String, val emoji: String)
data class SubFeatureTab(val id: String, val label: String, val icon: ImageVector)

@Composable
fun CreateScreen(activeFeature: String = "") {
    val artStyles = listOf(
        ArtStyle("anime", "Anime", "🌸", false),
        ArtStyle("oil-paint", "Oil Paint", "🎨", false),
        ArtStyle("watercolor", "Watercolor", "💧", false),
        ArtStyle("sketch", "Sketch", "✏️", false),
        ArtStyle("cyberpunk", "Cyberpunk", "🤖", true),
        ArtStyle("3d-render", "3D Render", "🎮", true),
        ArtStyle("vintage", "Vintage", "📷", false),
        ArtStyle("neon", "Neon Glow", "💜", true),
        ArtStyle("cartoon", "Cartoon", "🎭", false),
        ArtStyle("pixel", "Pixel Art", "👾", true),
        ArtStyle("impressionist", "Impressionist", "🌅", true),
        ArtStyle("pop-art", "Pop Art", "🎪", true),
    )

    val hairStyles = listOf(
        HairStyle("short", "Short Cut", "💈"),
        HairStyle("long", "Long Waves", "🌊"),
        HairStyle("curly", "Curly", "🌀"),
        HairStyle("bun", "Top Bun", "🎀"),
        HairStyle("mohawk", "Mohawk", "⚡"),
        HairStyle("afro", "Afro", "✨"),
    )

    val beardStyles = listOf(
        HairStyle("none", "Clean", "😊"),
        HairStyle("stubble", "Stubble", "🧔"),
        HairStyle("full", "Full Beard", "🧔"),
        HairStyle("goatee", "Goatee", "😎"),
        HairStyle("mustache", "Mustache", "🥸"),
    )

    val subFeatures = listOf(
        SubFeatureTab("art-styles", "Art Styles", Icons.Filled.Palette),
        SubFeatureTab("text-to-image", "Text→Image", Icons.Filled.TextFields),
        SubFeatureTab("cartoon", "Cartoon", Icons.Filled.Movie),
        SubFeatureTab("future-baby", "Future Baby", Icons.Filled.ChildCare),
        SubFeatureTab("hair-style", "Hair & Beard", Icons.Filled.Person),
    )

    var currentFeature by remember {
        mutableStateOf(if (activeFeature.isNotEmpty()) activeFeature else "art-styles")
    }
    var selectedStyle by remember { mutableStateOf("anime") }
    var selectedHair by remember { mutableStateOf("short") }
    var selectedBeard by remember { mutableStateOf("none") }
    var textPrompt by remember { mutableStateOf("") }
    var isProcessing by remember { mutableStateOf(false) }
    var isGenerated by remember { mutableStateOf(false) }
    var imageUploaded by remember { mutableStateOf(false) }
    var styleIntensity by remember { mutableStateOf(0.75f) }
    val scope = rememberCoroutineScope()

    fun handleProcess() {
        isProcessing = true
        isGenerated = false
        scope.launch {
            delay(2500)
            isProcessing = false
            isGenerated = true
        }
    }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(BgPrimary)
    ) {
        // Header
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 20.dp, vertical = 16.dp)
        ) {
            Text(
                "Create",
                fontSize = 20.sp,
                fontWeight = FontWeight.Bold,
                style = LocalTextStyle.current.copy(
                    brush = Brush.linearGradient(colors = listOf(AccentPurple, AccentPink))
                )
            )
            Text("AI-powered creation tools", fontSize = 12.sp, color = TextSecondary)
            Spacer(modifier = Modifier.height(12.dp))

            // Sub-feature tabs
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .horizontalScroll(rememberScrollState()),
                horizontalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                subFeatures.forEach { feat ->
                    val isActive = currentFeature == feat.id
                    Row(
                        modifier = Modifier
                            .clip(RoundedCornerShape(12.dp))
                            .background(
                                if (isActive) Brush.linearGradient(
                                    colors = listOf(AccentPurple, AccentPink)
                                ) else Brush.linearGradient(
                                    colors = listOf(BgCard, BgCard)
                                )
                            )
                            .then(
                                if (!isActive) Modifier.border(1.dp, BorderColor, RoundedCornerShape(12.dp))
                                else Modifier
                            )
                            .clickable {
                                currentFeature = feat.id
                                isGenerated = false
                                imageUploaded = false
                            }
                            .padding(horizontal = 12.dp, vertical = 6.dp),
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.spacedBy(4.dp)
                    ) {
                        Icon(
                            feat.icon,
                            contentDescription = feat.label,
                            tint = if (isActive) Color.White else TextSecondary,
                            modifier = Modifier.size(12.dp)
                        )
                        Text(
                            feat.label,
                            fontSize = 11.sp,
                            fontWeight = FontWeight.Medium,
                            color = if (isActive) Color.White else TextSecondary
                        )
                    }
                }
            }
        }

        // Content
        Column(
            modifier = Modifier
                .fillMaxSize()
                .verticalScroll(rememberScrollState())
                .padding(horizontal = 20.dp)
                .padding(bottom = 16.dp)
        ) {
            when (currentFeature) {
                "art-styles" -> ArtStylesContent(
                    artStyles = artStyles,
                    selectedStyle = selectedStyle,
                    onStyleSelect = { selectedStyle = it },
                    imageUploaded = imageUploaded,
                    onUpload = { imageUploaded = true; isGenerated = false },
                    isProcessing = isProcessing,
                    isGenerated = isGenerated,
                    styleIntensity = styleIntensity,
                    onIntensityChange = { styleIntensity = it },
                    onGenerate = { handleProcess() },
                    selectedStyleName = artStyles.find { it.id == selectedStyle }?.name ?: ""
                )
                "text-to-image" -> TextToImageContent(
                    textPrompt = textPrompt,
                    onPromptChange = { textPrompt = it },
                    isProcessing = isProcessing,
                    isGenerated = isGenerated,
                    onGenerate = { handleProcess() }
                )
                "cartoon" -> CartoonContent(
                    imageUploaded = imageUploaded,
                    onUpload = { imageUploaded = true; isGenerated = false },
                    isProcessing = isProcessing,
                    isGenerated = isGenerated,
                    onGenerate = { handleProcess() }
                )
                "future-baby" -> FutureBabyContent(
                    imageUploaded = imageUploaded,
                    onUpload = { imageUploaded = true; isGenerated = false },
                    isProcessing = isProcessing,
                    isGenerated = isGenerated,
                    onGenerate = { handleProcess() }
                )
                "hair-style" -> HairStyleContent(
                    hairStyles = hairStyles,
                    beardStyles = beardStyles,
                    selectedHair = selectedHair,
                    selectedBeard = selectedBeard,
                    onHairSelect = { selectedHair = it },
                    onBeardSelect = { selectedBeard = it },
                    imageUploaded = imageUploaded,
                    onUpload = { imageUploaded = true; isGenerated = false },
                    isProcessing = isProcessing,
                    isGenerated = isGenerated,
                    onGenerate = { handleProcess() }
                )
            }
        }
    }
}

@Composable
fun UploadArea(
    imageUploaded: Boolean,
    onUpload: () -> Unit,
    height: Int = 160
) {
    Box(
        modifier = Modifier
            .fillMaxWidth()
            .height(height.dp)
            .clip(RoundedCornerShape(16.dp))
            .background(Color(0x1A7C3AED))
            .border(
                width = 2.dp,
                brush = Brush.linearGradient(
                    colors = listOf(Color(0x4D7C3AED), Color(0x4DEC4899))
                ),
                shape = RoundedCornerShape(16.dp)
            )
            .clickable(onClick = onUpload),
        contentAlignment = Alignment.Center
    ) {
        if (imageUploaded) {
            Row(
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                Box(
                    modifier = Modifier
                        .size(64.dp)
                        .background(Color(0x337C3AED), RoundedCornerShape(12.dp)),
                    contentAlignment = Alignment.Center
                ) {
                    Text("🤳", fontSize = 28.sp)
                }
                Column {
                    Text("Photo ready!", fontSize = 13.sp, fontWeight = FontWeight.SemiBold, color = TextPrimary)
                    Text("Tap to change photo", fontSize = 11.sp, color = TextSecondary)
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.spacedBy(4.dp),
                        modifier = Modifier.padding(top = 4.dp)
                    ) {
                        Icon(Icons.Filled.Check, contentDescription = null, tint = AccentGreen, modifier = Modifier.size(12.dp))
                        Text("Selfie detected", fontSize = 11.sp, color = AccentGreen)
                    }
                }
            }
        } else {
            Column(
                horizontalAlignment = Alignment.CenterHorizontally,
                verticalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                Box(
                    modifier = Modifier
                        .size(56.dp)
                        .background(Color(0x267C3AED), RoundedCornerShape(16.dp)),
                    contentAlignment = Alignment.Center
                ) {
                    Icon(Icons.Filled.CameraAlt, contentDescription = null, tint = AccentPurple, modifier = Modifier.size(28.dp))
                }
                Text("Upload your selfie", fontSize = 13.sp, fontWeight = FontWeight.SemiBold, color = TextPrimary)
                Text("Tap to take photo or choose from gallery", fontSize = 11.sp, color = TextSecondary)
                Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                    Row(
                        modifier = Modifier
                            .background(Color(0x337C3AED), RoundedCornerShape(8.dp))
                            .padding(horizontal = 12.dp, vertical = 6.dp),
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.spacedBy(4.dp)
                    ) {
                        Icon(Icons.Filled.CameraAlt, contentDescription = null, tint = PurpleLight, modifier = Modifier.size(12.dp))
                        Text("Camera", fontSize = 11.sp, color = PurpleLight)
                    }
                    Row(
                        modifier = Modifier
                            .background(Color(0x337C3AED), RoundedCornerShape(8.dp))
                            .padding(horizontal = 12.dp, vertical = 6.dp),
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.spacedBy(4.dp)
                    ) {
                        Icon(Icons.Filled.Upload, contentDescription = null, tint = PurpleLight, modifier = Modifier.size(12.dp))
                        Text("Gallery", fontSize = 11.sp, color = PurpleLight)
                    }
                }
            }
        }
    }
}

@Composable
fun GenerateButton(
    isProcessing: Boolean,
    onClick: () -> Unit,
    label: String = "Generate Art",
    processingLabel: String = "Generating AI Art...",
    gradientColors: List<Color> = listOf(AccentPurple, AccentPink)
) {
    Button(
        onClick = onClick,
        enabled = !isProcessing,
        colors = ButtonDefaults.buttonColors(containerColor = Color.Transparent),
        modifier = Modifier
            .fillMaxWidth()
            .height(52.dp)
            .background(
                Brush.linearGradient(colors = gradientColors),
                RoundedCornerShape(12.dp)
            ),
        contentPadding = PaddingValues(0.dp)
    ) {
        if (isProcessing) {
            CircularProgressIndicator(
                modifier = Modifier.size(18.dp),
                color = Color.White,
                strokeWidth = 2.dp
            )
            Spacer(modifier = Modifier.width(8.dp))
            Text(processingLabel, fontSize = 14.sp, fontWeight = FontWeight.SemiBold)
        } else {
            Icon(Icons.Filled.AutoAwesome, contentDescription = null, modifier = Modifier.size(18.dp))
            Spacer(modifier = Modifier.width(8.dp))
            Text(label, fontSize = 14.sp, fontWeight = FontWeight.SemiBold)
        }
    }
}

@Composable
fun GeneratedResultCard(
    emoji: String,
    title: String,
    subtitle: String,
    accentColor: Color = AccentGreen
) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(16.dp))
            .background(accentColor.copy(alpha = 0.1f))
            .border(1.dp, accentColor.copy(alpha = 0.3f), RoundedCornerShape(16.dp))
            .padding(16.dp),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.spacedBy(12.dp)
    ) {
        Text(emoji, fontSize = 36.sp)
        Column(modifier = Modifier.weight(1f)) {
            Text(title, fontSize = 13.sp, fontWeight = FontWeight.SemiBold, color = accentColor)
            Text(subtitle, fontSize = 11.sp, color = TextSecondary)
        }
        Button(
            onClick = {},
            colors = ButtonDefaults.buttonColors(containerColor = Color.Transparent),
            modifier = Modifier.background(
                Brush.linearGradient(colors = listOf(AccentGreen, AccentCyan)),
                RoundedCornerShape(8.dp)
            ),
            contentPadding = PaddingValues(horizontal = 12.dp, vertical = 6.dp)
        ) {
            Text("Save", fontSize = 11.sp, fontWeight = FontWeight.Bold)
        }
    }
}

@Composable
fun ArtStylesContent(
    artStyles: List<ArtStyle>,
    selectedStyle: String,
    onStyleSelect: (String) -> Unit,
    imageUploaded: Boolean,
    onUpload: () -> Unit,
    isProcessing: Boolean,
    isGenerated: Boolean,
    styleIntensity: Float,
    onIntensityChange: (Float) -> Unit,
    onGenerate: () -> Unit,
    selectedStyleName: String
) {
    UploadArea(imageUploaded = imageUploaded, onUpload = onUpload)
    Spacer(modifier = Modifier.height(16.dp))

    Text("Choose Art Style", fontSize = 13.sp, fontWeight = FontWeight.SemiBold, color = TextPrimary)
    Spacer(modifier = Modifier.height(12.dp))

    // 3-column grid
    val rows = artStyles.chunked(3)
    rows.forEach { row ->
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            row.forEach { style ->
                val isSelected = selectedStyle == style.id
                Box(
                    modifier = Modifier
                        .weight(1f)
                        .clip(RoundedCornerShape(12.dp))
                        .background(
                            if (isSelected) Color(0x337C3AED) else BgCard
                        )
                        .border(
                            1.dp,
                            if (isSelected) Color(0x997C3AED) else BorderColor,
                            RoundedCornerShape(12.dp)
                        )
                        .clickable { onStyleSelect(style.id) }
                        .padding(12.dp)
                ) {
                    if (style.premium) {
                        Box(
                            modifier = Modifier
                                .align(Alignment.TopEnd)
                                .background(
                                    Brush.linearGradient(colors = listOf(AccentAmber, AccentOrange)),
                                    RoundedCornerShape(4.dp)
                                )
                                .padding(horizontal = 4.dp, vertical = 1.dp)
                        ) {
                            Text("PRO", fontSize = 7.sp, fontWeight = FontWeight.Bold, color = Color.White)
                        }
                    }
                    Column(
                        horizontalAlignment = Alignment.CenterHorizontally,
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Text(style.emoji, fontSize = 20.sp)
                        Spacer(modifier = Modifier.height(4.dp))
                        Text(
                            style.name,
                            fontSize = 10.sp,
                            fontWeight = FontWeight.Medium,
                            color = if (isSelected) PurpleLight else TextSecondary
                        )
                    }
                }
            }
            // Fill remaining cells if row is not full
            repeat(3 - row.size) {
                Spacer(modifier = Modifier.weight(1f))
            }
        }
        Spacer(modifier = Modifier.height(8.dp))
    }

    Spacer(modifier = Modifier.height(8.dp))

    // Intensity Slider
    Row(
        modifier = Modifier.fillMaxWidth(),
        horizontalArrangement = Arrangement.SpaceBetween,
        verticalAlignment = Alignment.CenterVertically
    ) {
        Text("Style Intensity", fontSize = 13.sp, fontWeight = FontWeight.Medium, color = TextPrimary)
        Text("${(styleIntensity * 100).toInt()}%", fontSize = 13.sp, fontWeight = FontWeight.Bold, color = PurpleLight)
    }
    Slider(
        value = styleIntensity,
        onValueChange = onIntensityChange,
        colors = SliderDefaults.colors(
            thumbColor = AccentPurple,
            activeTrackColor = AccentPurple,
            inactiveTrackColor = BorderColor
        )
    )

    Spacer(modifier = Modifier.height(8.dp))
    GenerateButton(
        isProcessing = isProcessing,
        onClick = onGenerate,
        label = if (imageUploaded) "Generate Art" else "Upload & Generate"
    )

    if (isGenerated) {
        Spacer(modifier = Modifier.height(16.dp))
        GeneratedResultCard(
            emoji = "🎨",
            title = "✨ Art Generated!",
            subtitle = "Your $selectedStyleName style is ready"
        )
    }
}

@Composable
fun TextToImageContent(
    textPrompt: String,
    onPromptChange: (String) -> Unit,
    isProcessing: Boolean,
    isGenerated: Boolean,
    onGenerate: () -> Unit
) {
    // Info banner
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(16.dp))
            .background(
                Brush.linearGradient(
                    colors = listOf(Color(0x1A06B6D4), Color(0x1A7C3AED))
                )
            )
            .border(1.dp, Color(0x4D06B6D4), RoundedCornerShape(16.dp))
            .padding(16.dp),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.spacedBy(8.dp)
    ) {
        Icon(Icons.Filled.AutoAwesome, contentDescription = null, tint = AccentCyan, modifier = Modifier.size(16.dp))
        Column {
            Text("AI Image Generator", fontSize = 13.sp, fontWeight = FontWeight.SemiBold, color = AccentCyan)
            Text("Describe any image and our AI will create it for you", fontSize = 11.sp, color = TextSecondary)
        }
    }

    Spacer(modifier = Modifier.height(16.dp))

    Text("Describe your image", fontSize = 13.sp, fontWeight = FontWeight.Medium, color = TextPrimary)
    Spacer(modifier = Modifier.height(8.dp))

    OutlinedTextField(
        value = textPrompt,
        onValueChange = onPromptChange,
        placeholder = { Text("e.g., A futuristic portrait with neon lights, cyberpunk style...", fontSize = 12.sp, color = TextMuted) },
        modifier = Modifier
            .fillMaxWidth()
            .height(120.dp),
        colors = OutlinedTextFieldDefaults.colors(
            focusedBorderColor = AccentPurple,
            unfocusedBorderColor = BorderColor,
            focusedTextColor = TextPrimary,
            unfocusedTextColor = TextPrimary,
            cursorColor = AccentPurple,
            focusedContainerColor = BgCard,
            unfocusedContainerColor = BgCard
        ),
        shape = RoundedCornerShape(12.dp),
        maxLines = 5
    )
    Row(
        modifier = Modifier.fillMaxWidth(),
        horizontalArrangement = Arrangement.SpaceBetween
    ) {
        Text("Be descriptive for better results", fontSize = 10.sp, color = TextMuted)
        Text("${textPrompt.length}/500", fontSize = 10.sp, color = TextMuted)
    }

    Spacer(modifier = Modifier.height(16.dp))

    Text("Style Preset", fontSize = 13.sp, fontWeight = FontWeight.SemiBold, color = TextPrimary)
    Spacer(modifier = Modifier.height(8.dp))

    Row(
        modifier = Modifier
            .fillMaxWidth()
            .horizontalScroll(rememberScrollState()),
        horizontalArrangement = Arrangement.spacedBy(8.dp)
    ) {
        listOf(
            Pair("📸", "Realistic"),
            Pair("🌸", "Anime"),
            Pair("🖥️", "Digital Art"),
            Pair("🧙", "Fantasy"),
            Pair("🚀", "Sci-Fi"),
            Pair("👤", "Portrait")
        ).forEach { (emoji, name) ->
            Row(
                modifier = Modifier
                    .clip(RoundedCornerShape(50))
                    .background(BgCard)
                    .border(1.dp, BorderColor, RoundedCornerShape(50))
                    .padding(horizontal = 12.dp, vertical = 6.dp),
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.spacedBy(4.dp)
            ) {
                Text(emoji, fontSize = 12.sp)
                Text(name, fontSize = 11.sp, color = TextSecondary)
            }
        }
    }

    Spacer(modifier = Modifier.height(16.dp))

    Text("Image Size", fontSize = 13.sp, fontWeight = FontWeight.SemiBold, color = TextPrimary)
    Spacer(modifier = Modifier.height(8.dp))

    Row(
        modifier = Modifier.fillMaxWidth(),
        horizontalArrangement = Arrangement.spacedBy(8.dp)
    ) {
        listOf(
            Triple("⬛", "Square", "1:1"),
            Triple("📱", "Portrait", "3:4"),
            Triple("🖼️", "Landscape", "4:3")
        ).forEachIndexed { index, (icon, label, ratio) ->
            val isSelected = index == 0
            Column(
                modifier = Modifier
                    .weight(1f)
                    .clip(RoundedCornerShape(12.dp))
                    .background(if (isSelected) Color(0x337C3AED) else BgCard)
                    .border(
                        1.dp,
                        if (isSelected) Color(0x997C3AED) else BorderColor,
                        RoundedCornerShape(12.dp)
                    )
                    .padding(8.dp),
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                Text(icon, fontSize = 18.sp)
                Text(label, fontSize = 11.sp, fontWeight = FontWeight.Medium, color = TextPrimary)
                Text(ratio, fontSize = 9.sp, color = TextMuted)
            }
        }
    }

    Spacer(modifier = Modifier.height(16.dp))

    Text("Try These Prompts", fontSize = 13.sp, fontWeight = FontWeight.SemiBold, color = TextPrimary)
    Spacer(modifier = Modifier.height(8.dp))

    listOf(
        "A glowing portrait with aurora borealis background",
        "Futuristic city at night with neon reflections",
        "Magical forest with floating lanterns"
    ).forEach { prompt ->
        Box(
            modifier = Modifier
                .fillMaxWidth()
                .clip(RoundedCornerShape(12.dp))
                .background(BgCard)
                .border(1.dp, BorderColor, RoundedCornerShape(12.dp))
                .clickable { /* onPromptChange(prompt) */ }
                .padding(12.dp)
        ) {
            Text("💡 $prompt", fontSize = 11.sp, color = TextSecondary)
        }
        Spacer(modifier = Modifier.height(8.dp))
    }

    GenerateButton(
        isProcessing = isProcessing,
        onClick = onGenerate,
        label = "Generate Image",
        processingLabel = "Creating Image...",
        gradientColors = listOf(AccentCyan, AccentPurple)
    )

    if (isGenerated) {
        Spacer(modifier = Modifier.height(16.dp))
        GeneratedResultCard(
            emoji = "🖼️",
            title = "Image Generated!",
            subtitle = "Your AI artwork is ready",
            accentColor = AccentCyan
        )
    }
}

@Composable
fun CartoonContent(
    imageUploaded: Boolean,
    onUpload: () -> Unit,
    isProcessing: Boolean,
    isGenerated: Boolean,
    onGenerate: () -> Unit
) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(16.dp))
            .background(Color(0x1AEC4899))
            .border(1.dp, Color(0x4DEC4899), RoundedCornerShape(16.dp))
            .padding(16.dp),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.spacedBy(8.dp)
    ) {
        Text("🎨", fontSize = 24.sp)
        Column {
            Text("Cartoon Style", fontSize = 13.sp, fontWeight = FontWeight.SemiBold, color = AccentPink)
            Text("Transform your photo into animated cartoon art", fontSize = 11.sp, color = TextSecondary)
        }
    }
    Spacer(modifier = Modifier.height(16.dp))

    UploadArea(imageUploaded = imageUploaded, onUpload = onUpload)
    Spacer(modifier = Modifier.height(16.dp))

    Text("Cartoon Style", fontSize = 13.sp, fontWeight = FontWeight.SemiBold, color = TextPrimary)
    Spacer(modifier = Modifier.height(8.dp))

    Row(
        modifier = Modifier.fillMaxWidth(),
        horizontalArrangement = Arrangement.spacedBy(8.dp)
    ) {
        listOf(
            Pair("🎭", "Disney"),
            Pair("🌸", "Anime"),
            Pair("🎪", "Comic"),
            Pair("🎬", "Pixar")
        ).forEachIndexed { index, (emoji, name) ->
            Column(
                modifier = Modifier
                    .weight(1f)
                    .clip(RoundedCornerShape(12.dp))
                    .background(if (index == 0) Color(0x33EC4899) else BgCard)
                    .border(
                        1.dp,
                        if (index == 0) Color(0x99EC4899) else BorderColor,
                        RoundedCornerShape(12.dp)
                    )
                    .padding(8.dp),
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                Text(emoji, fontSize = 20.sp)
                Text(name, fontSize = 10.sp, color = if (index == 0) AccentPink else TextSecondary)
            }
        }
    }

    Spacer(modifier = Modifier.height(16.dp))
    GenerateButton(
        isProcessing = isProcessing,
        onClick = onGenerate,
        label = "Cartoonify",
        processingLabel = "Creating Cartoon...",
        gradientColors = listOf(AccentPink, AccentPurple)
    )

    if (isGenerated) {
        Spacer(modifier = Modifier.height(16.dp))
        GeneratedResultCard(
            emoji = "🎭",
            title = "Cartoon Created!",
            subtitle = "Your cartoon portrait is ready",
            accentColor = AccentPink
        )
    }
}

@Composable
fun FutureBabyContent(
    imageUploaded: Boolean,
    onUpload: () -> Unit,
    isProcessing: Boolean,
    isGenerated: Boolean,
    onGenerate: () -> Unit
) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(16.dp))
            .background(Color(0x1AF59E0B))
            .border(1.dp, Color(0x4DF59E0B), RoundedCornerShape(16.dp))
            .padding(16.dp),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.spacedBy(8.dp)
    ) {
        Text("👶", fontSize = 24.sp)
        Column {
            Text("Future Baby", fontSize = 13.sp, fontWeight = FontWeight.SemiBold, color = AccentAmber)
            Text("Generate your future baby portrait with AI", fontSize = 11.sp, color = TextSecondary)
        }
    }
    Spacer(modifier = Modifier.height(16.dp))

    Text("Upload Parent Photos", fontSize = 13.sp, fontWeight = FontWeight.SemiBold, color = TextPrimary)
    Spacer(modifier = Modifier.height(8.dp))

    Row(
        modifier = Modifier.fillMaxWidth(),
        horizontalArrangement = Arrangement.spacedBy(12.dp)
    ) {
        Column(modifier = Modifier.weight(1f)) {
            Text("Parent 1", fontSize = 11.sp, color = TextSecondary, modifier = Modifier.padding(bottom = 6.dp))
            UploadArea(imageUploaded = imageUploaded, onUpload = onUpload, height = 120)
        }
        Column(modifier = Modifier.weight(1f)) {
            Text("Parent 2 (Optional)", fontSize = 11.sp, color = TextSecondary, modifier = Modifier.padding(bottom = 6.dp))
            UploadArea(imageUploaded = false, onUpload = {}, height = 120)
        }
    }

    Spacer(modifier = Modifier.height(16.dp))

    Text("Baby Age", fontSize = 13.sp, fontWeight = FontWeight.SemiBold, color = TextPrimary)
    Spacer(modifier = Modifier.height(8.dp))

    Row(
        modifier = Modifier.fillMaxWidth(),
        horizontalArrangement = Arrangement.spacedBy(8.dp)
    ) {
        listOf("Newborn", "1 Year", "3 Years", "5 Years").forEachIndexed { index, age ->
            Box(
                modifier = Modifier
                    .weight(1f)
                    .clip(RoundedCornerShape(8.dp))
                    .background(if (index == 0) Color(0x33F59E0B) else BgCard)
                    .border(
                        1.dp,
                        if (index == 0) Color(0x99F59E0B) else BorderColor,
                        RoundedCornerShape(8.dp)
                    )
                    .padding(vertical = 8.dp),
                contentAlignment = Alignment.Center
            ) {
                Text(age, fontSize = 10.sp, color = if (index == 0) AccentAmber else TextSecondary)
            }
        }
    }

    Spacer(modifier = Modifier.height(16.dp))
    GenerateButton(
        isProcessing = isProcessing,
        onClick = onGenerate,
        label = "Generate Baby",
        processingLabel = "Generating Baby...",
        gradientColors = listOf(AccentAmber, AccentOrange)
    )

    if (isGenerated) {
        Spacer(modifier = Modifier.height(16.dp))
        GeneratedResultCard(
            emoji = "👶",
            title = "Baby Generated!",
            subtitle = "Your future baby portrait is ready",
            accentColor = AccentAmber
        )
    }
}

@Composable
fun HairStyleContent(
    hairStyles: List<HairStyle>,
    beardStyles: List<HairStyle>,
    selectedHair: String,
    selectedBeard: String,
    onHairSelect: (String) -> Unit,
    onBeardSelect: (String) -> Unit,
    imageUploaded: Boolean,
    onUpload: () -> Unit,
    isProcessing: Boolean,
    isGenerated: Boolean,
    onGenerate: () -> Unit
) {
    UploadArea(imageUploaded = imageUploaded, onUpload = onUpload)
    Spacer(modifier = Modifier.height(16.dp))

    Text("Hair Style", fontSize = 13.sp, fontWeight = FontWeight.SemiBold, color = TextPrimary)
    Spacer(modifier = Modifier.height(8.dp))

    Row(
        modifier = Modifier
            .fillMaxWidth()
            .horizontalScroll(rememberScrollState()),
        horizontalArrangement = Arrangement.spacedBy(8.dp)
    ) {
        hairStyles.forEach { style ->
            val isSelected = selectedHair == style.id
            Column(
                modifier = Modifier
                    .clip(RoundedCornerShape(12.dp))
                    .background(if (isSelected) Color(0x337C3AED) else BgCard)
                    .border(
                        1.dp,
                        if (isSelected) Color(0x997C3AED) else BorderColor,
                        RoundedCornerShape(12.dp)
                    )
                    .clickable { onHairSelect(style.id) }
                    .padding(12.dp),
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                Text(style.emoji, fontSize = 20.sp)
                Text(style.name, fontSize = 10.sp, color = if (isSelected) PurpleLight else TextSecondary)
            }
        }
    }

    Spacer(modifier = Modifier.height(16.dp))

    Text("Beard Style", fontSize = 13.sp, fontWeight = FontWeight.SemiBold, color = TextPrimary)
    Spacer(modifier = Modifier.height(8.dp))

    Row(
        modifier = Modifier
            .fillMaxWidth()
            .horizontalScroll(rememberScrollState()),
        horizontalArrangement = Arrangement.spacedBy(8.dp)
    ) {
        beardStyles.forEach { style ->
            val isSelected = selectedBeard == style.id
            Column(
                modifier = Modifier
                    .clip(RoundedCornerShape(12.dp))
                    .background(if (isSelected) Color(0x337C3AED) else BgCard)
                    .border(
                        1.dp,
                        if (isSelected) Color(0x997C3AED) else BorderColor,
                        RoundedCornerShape(12.dp)
                    )
                    .clickable { onBeardSelect(style.id) }
                    .padding(12.dp),
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                Text(style.emoji, fontSize = 20.sp)
                Text(style.name, fontSize = 10.sp, color = if (isSelected) PurpleLight else TextSecondary)
            }
        }
    }

    Spacer(modifier = Modifier.height(16.dp))
    GenerateButton(
        isProcessing = isProcessing,
        onClick = onGenerate,
        label = "Apply Style",
        processingLabel = "Applying Style..."
    )

    if (isGenerated) {
        Spacer(modifier = Modifier.height(16.dp))
        GeneratedResultCard(
            emoji = "💇",
            title = "Style Applied!",
            subtitle = "Your new look is ready"
        )
    }
}
